spring:
  application:
    name: desafio-dev-api
  datasource:
    password: 
    url: jdbc:mysql://127.0.0.1:3306/desafio-dev?useTimezone=true&serverTimezone=GMT-3
    username: root
  jpa:
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        formatSql: false
    showSql: false
    openInView: false

server:
  port: 8080